#pragma once

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "driver/spi_master.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BOARD_EPD_WIDTH  200
#define BOARD_EPD_HEIGHT 200

#define BOARD_EPD_SPI_HOST SPI2_HOST
#define BOARD_EPD_DC_PIN   GPIO_NUM_10
#define BOARD_EPD_CS_PIN   GPIO_NUM_11
#define BOARD_EPD_SCK_PIN  GPIO_NUM_12
#define BOARD_EPD_MOSI_PIN GPIO_NUM_13
#define BOARD_EPD_RST_PIN  GPIO_NUM_9
#define BOARD_EPD_BUSY_PIN GPIO_NUM_8

#define BOARD_EPD_PWR_PIN GPIO_NUM_6
#define BOARD_AUDIO_PWR_PIN GPIO_NUM_42
#define BOARD_VBAT_PWR_PIN GPIO_NUM_17
#define BOARD_BAT_ADC_PIN GPIO_NUM_4

#define BOARD_BOOT_BUTTON_PIN GPIO_NUM_0
#define BOARD_PWR_BUTTON_PIN  GPIO_NUM_18
#define BOARD_RTC_INT_PIN     GPIO_NUM_5

#define BOARD_I2C_SDA_PIN GPIO_NUM_47
#define BOARD_I2C_SCL_PIN GPIO_NUM_48
#define BOARD_I2C_PORT    I2C_NUM_0
#define BOARD_I2C_SPEED_HZ 400000

#define BOARD_RTC_I2C_ADDR    0x51
#define BOARD_SHTC3_I2C_ADDR  0x70
#define BOARD_FT6336_I2C_ADDR 0x38

#define BOARD_EPD_TP_RST_PIN GPIO_NUM_7
#define BOARD_EPD_TP_INT_PIN GPIO_NUM_21

#define BOARD_SD_CLK_PIN  GPIO_NUM_39
#define BOARD_SD_MISO_PIN GPIO_NUM_40
#define BOARD_SD_MOSI_PIN GPIO_NUM_41

#define BOARD_I2S_MCLK_PIN  GPIO_NUM_14
#define BOARD_I2S_SCLK_PIN  GPIO_NUM_15
#define BOARD_I2S_ASDOUT_PIN GPIO_NUM_16
#define BOARD_I2S_LRCK_PIN  GPIO_NUM_38
#define BOARD_I2S_DSDIN_PIN GPIO_NUM_45
#define BOARD_PA_CTRL_PIN   GPIO_NUM_46
#define BOARD_PA_EN_PIN     GPIO_NUM_42

#ifdef __cplusplus
}
#endif
